# CI workflow with separate jobs for each test file

name: CI

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
      - name: "Install modules"
        run: "npm install"
      - name: "Build (npm)"
        run: "npm run build"
      - name: "Cache build"
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            packages/*/dist
          key: build-${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build
    name: "Test: ${{ matrix.test }}"
    strategy:
      fail-fast: false
      matrix:
        test:
          - counterCrdt.additional
          - counterCrdt
          - ecdh
          - encoding
          - groupKey
          - hex
          - lifecycle-api
          - listCrdt.additional
          - listCrdt
          - mapCrdt.additional
          - mapCrdt
          - network-base
          - network.additional
          - network
          - pow
          - sha1
          - sha256
          - signup-local-first
          - store
          - textRandom
          - verify
    steps:
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
      - name: "Restore build cache"
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            packages/*/dist
          key: build-${{ github.sha }}
      - name: "Run test"
        run: npx jest __tests__/${{ matrix.test }}.ts

  deploy:
    runs-on: ubuntu-latest
    needs: test
    name: "Deploy"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
      - name: "Install example modules"
        run: npm install && npm run build && cd example && npm install
      - name: "Build example"
        run: cd example && npm run build
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: Manwe-777/tool-db-chat-example
          publish_branch: main
          publish_dir: ./example/build
